// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD99QhAfr1CFa133LnndJeELrjY_PA6x8Y',
    appId: '1:121286195241:web:95cd33feda9e9383b6c438',
    messagingSenderId: '121286195241',
    projectId: 'vsphere-8a9cd',
    authDomain: 'vsphere-8a9cd.firebaseapp.com',
    storageBucket: 'vsphere-8a9cd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDseYOETNyq4wBPproqfvFPL3fZRaQ87Ec',
    appId: '1:121286195241:android:38b911505861f5d5b6c438',
    messagingSenderId: '121286195241',
    projectId: 'vsphere-8a9cd',
    storageBucket: 'vsphere-8a9cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPnHJn6k2IshPVDsqHhBf3CyrR8d9SmrI',
    appId: '1:121286195241:ios:c45878353b125ff6b6c438',
    messagingSenderId: '121286195241',
    projectId: 'vsphere-8a9cd',
    storageBucket: 'vsphere-8a9cd.appspot.com',
    iosBundleId: 'com.example.myvoiceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPnHJn6k2IshPVDsqHhBf3CyrR8d9SmrI',
    appId: '1:121286195241:ios:c45878353b125ff6b6c438',
    messagingSenderId: '121286195241',
    projectId: 'vsphere-8a9cd',
    storageBucket: 'vsphere-8a9cd.appspot.com',
    iosBundleId: 'com.example.myvoiceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD99QhAfr1CFa133LnndJeELrjY_PA6x8Y',
    appId: '1:121286195241:web:5a385a3fc8399c09b6c438',
    messagingSenderId: '121286195241',
    projectId: 'vsphere-8a9cd',
    authDomain: 'vsphere-8a9cd.firebaseapp.com',
    storageBucket: 'vsphere-8a9cd.appspot.com',
  );

}